title:              "진한문장"
tagline:            "기억에 남는 글을 씁니다"
email:              "dhkang810@gmail.com"
description:        "기억에 남는 진한문장을 만듭니다"
author:             "jhmj"
baseurl:            "/"
url:                "https://jhmj.space"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.png"

# Social Profiles


# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
# 블로그 disqus shortname
disqus:
  shortname: jhmj-space-3
